name: Fly Deploy
on:
  push:
    branches:
      - main
      - initial_setup
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd express
      - run: flyctl deploy --remote-only