name: Deploy to Fly

on:
  push:
    branches:
    - main
    - frontend-deployment
  pull_request:
    branches:
    - main

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy proxy
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd frontend
      - run: fly deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}